# Use an official Python runtime as a parent image
FROM python:3.9

# The environment variable ensures that the python output is set straight
# to the terminal without buffering it first
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN mkdir /app

WORKDIR /app

# Copy only requirements to cache them in docker layer
COPY pyproject.toml poetry.lock* /app/

# Install dependencies
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

# Copy local code to the container image.
COPY ./rca_batch/ /app/rca_batch/

# Create a non-root user
RUN useradd -m appuser

# Change owner of the /app directory
RUN chown -R appuser /app

# Switch to the non-root user
USER appuser

# Set start command
CMD ["poetry", "run", "start"]
