apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: default
spec:
  encryptedData:
    aws_access_key_id: AgBAMHRcotrDhoiLVc1AElzwLbThs7q7TjiDj/10TByJv8oQ5LD1jEkFNwhgwXFn805uGdAYpMcwO8JTRGBZLZX6NAwDjoACbTzT5u1GzHfsE22sKBVPURUUSEZBWEXaKsPWl/OBfgNtbYcQPlEshrYZzwDjSnp9uoxoRhSsUrVQwI/NMupxTholRAMy732WbAmgymU34LHWbhUuy3saD7p5QZFCSNmX6pqXLsdQSg/uNMVjdJoYLOXNk5dGhd5SSBx4qwaIHm8jk6lERduoyuHqGXFHApBhBtJMtlPK19rjAoAZUAXw8gpmOjS64hhn3CZs58Iy+kz+bD5xNp2UJiEEgNRXOU7ePEH87IDfbEX/5/gpsKa0hfcUn+LjvpWVWi+7uZXmAkXgLVQ1PG4GvSL6vw+CVMOampkBklIYk4089wTDiAz7n8m2BePteIstKX5jdJqVVnBMjLDktklCV4jdmvd1+QGKBx7kxFTuo14c37oOCOlBpd9abNGTpLmwKeRDBHdBiXJCcxRj0RSa1AHpbyzmf9VWDpUtrte9PHMlAfT7MqLHvqKeezSxshJBvdg2RlpOGa2cQLuGr9VQDRd6MN3fRhzbR8qPcDAlqLbHXoU9S5YcurqklDVRCdpX84qNouw6QINY874Zhu7mENWUIrZhujszGmlbvBZkoSh64pwnsijTmg6jVpnxoXUwOh/+1/7EzhOdevfPSwyW1X7ZfdD9EQ==
    aws_secret_access_key: AgCTzBnNdi2y6kMzECiHHoAqPtBjiZqKrareZ7JCPiIDiczBMYKkmrypw/6eFuDb8G1AqyTB4NTadNHRTEyOjFpVGdZa6RAzHv5AaMG6il2czebbehy5Gheyca6Fba0RuGLql9eTLaEokH/5CHl81hWKh68JN341gPsvJnY/Ox0DKKcKP64c8BN8ZqzPyCuYLB/pMahUpdxQqR2oeQ65KjGgXPPTLXiuDxUpdRihZw756hDDg2fODbWmNF89T8cIRCKK6foGe6sX1YbNvgAV35dluJ02FIwxevD0CwES6Q/RFewxwPeoAfYrNAesTfa6R91yuRht9csmEpN5cl/mxXz7/gq3bQdJQEoira80ZVHlnTSWoaUCxiC2VOjXM05rdnlvcHeXMySzoTLwc0GplUh8VE5RJnQ2gy7IdJQwh+SHThhtamhaxIv7dN9QkLnXFnl8AbEyor7qa25FsTBpOUyJwCLUuxae1MlqwyWk/19e0O6cwAF5ZsP/B+HKeYfNKO5SIIcbWsrzNBiIymT7GT/8b75N4bmVNdqCaVwJGhx0iDMgsS6p2UWskHxiU51hNCCBWFh48x6jxRlvpYxDH3yy3lPA6dx1RQRj1ILsXfhj/pNSWM2o74LpG9OirVWhOvFyhMFCCCmA0QPnSH7WLK7OmENxC4WyWcMN7VVNGvTCYONNhTZOzUjHhGPw/Z5wBsi6cNpdjBkySz8iGWZZLMEuAfR4PR6n9K5H0julN9S16h4zEIRiWhBy
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: default

