apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
- name: rca-batch-env
  env: .env.kube
generatorOptions:
  disableNameSuffixHash: true
patches:
- path: job-patch.yaml
  target:
    group: batch
    kind: Job
    name: rca-batch
    version: v1
